import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import AuthState from "./components/firebaseComponent/Context";
import { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.min.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthState>
            {children}
            <ToastContainer />
          </AuthState>
        </StoreProvider>
      </body>
    </html>
  );
}
